- src/main/java/fr/openent/crre/controllers/DevController.java
Permet de simuler une API moissonable par le moissonneur
API: https://confluence.support-ent.fr/display/CRRE/API+1.5.0
[CRRE-598](https://jira.support-ent.fr/browse/CRRE-598)
> feat(dev): #CRRE-598 add API for harvesting

- src/main/java/fr/openent/crre/controllers/DevController.java
Allows writing and reading of several statuses to simulate several libraries.
[CRRE-578](https://jira.support-ent.fr/browse/CRRE-578)
> feat: #CRRE-587 add multi status

- src/main/java/fr/openent/crre/core/constants/Field.java
- src/main/java/fr/openent/crre/helpers/ElasticSearchHelper.java
- src/main/java/fr/openent/crre/model/item/Offer.java
When the bookseller makes a mistake in one of these articles, the harvester does not filter the information. Here we add security.
[CRRE-601](https://jira.support-ent.fr/browse/CRRE-601)
> fix: #CRRE-601 add exclusion of items that do not have valid offers

- src/main/java/fr/openent/crre/controllers/OrderRegionController.java
- src/main/java/fr/openent/crre/core/constants/Field.java
- src/main/java/fr/openent/crre/helpers/EquipmentHelper.java
- src/main/java/fr/openent/crre/helpers/OrderHelper.java
- src/main/java/fr/openent/crre/model/OrderUniversalModel.java
- src/main/resources/public/template/prescriptor/basket/manage-basket.html
- src/main/resources/public/template/prescriptor/order/orders-list.html
- src/main/resources/public/template/validator/order-waiting.html
- src/main/resources/public/ts/controllers/validator/orders-waiting.ts
- src/main/resources/public/ts/model/Equipment.ts
- src/main/resources/public/ts/model/OrderClient.ts
- src/main/resources/public/ts/model/OrderUniversal.ts
When an article is no longer available, its price is set to 0. In some CRRE pages, we check whether the article exists and compare if the price is at 0. But now we can have articles that are naturally free.
API change: https://confluence.support-ent.fr/pages/diffpagesbyversion.action?pageId=158075571&selectedPageVersions=17&selectedPageVersions=16
As a prescriber, before validating the basket, make sure that an item is no longer available. The prescriber cannot validate this article and can only delete it.
As a prescriber, validate a basket and ensure that the item is no longer available. As a validator, I cannot change the quantity and I cannot place an order with this item. As a prescriber, I cannot modify the quantity of the article from the history.
With an article at 0€, I can …
> feat: #CRRE-602 add offer of free items in a campaign with credit

- src/main/java/fr/openent/crre/helpers/ElasticSearchHelper.java
- src/main/java/fr/openent/crre/model/item/Availability.java
- src/main/java/fr/openent/crre/model/item/Item.java
- src/main/java/fr/openent/crre/model/item/Offer.java
Some fields are mandatory for an article. We must exclude from CRRE the invalid articles to make them pass in article not found.
Fixed paper items being excluded because it had no offers when this is normal.
[CRRE-353](https://jira.support-ent.fr/browse/CRRE-353)
> fix: #CRRE-353 add security when item is without ean

- src/main/resources/i18n/timeline/en.json
- src/main/resources/i18n/timeline/fr.json
Changes the group name of the notifications of the timeline "CRRE -> Resources.num"
All notifications have the new group name
[CRRE-597](https://jira.support-ent.fr/browse/CRRE-597)
> feat: #CRRE-597 change crre notification title

- src/main/resources/public/template/administrator/order/order-waiting.html
- src/main/resources/public/ts/controllers/administrator/order/refuse-order.ts
- src/main/resources/public/ts/controllers/administrator/order/waitingOrder.ts
- src/main/resources/public/ts/controllers/prescriptor/order/manage-order.ts
- src/main/resources/public/ts/controllers/validator/order-historic.ts
- src/main/resources/public/ts/controllers/validator/order-to-region.ts
- src/main/resources/public/ts/directives/confirm-generate-library/confirm-generate-library.directive.ts
- src/main/resources/public/ts/directives/confirm-generate-library/confirm-generate-library.html
- src/main/resources/public/ts/enum/order-status-enum.ts
- src/main/resources/public/ts/model/Utils.ts
Added archived requests (administrator interface) + added filtering.
Addition of archived requests (validator interface).
Blocking actions on archived orders.
Have an order of each status:
WAITING // Basket validated
REJECTED // Command refused by the administrator
IN_PROGRESS // Command validated by the validator
VALID // Order validated by the administrator
SENT // Order sent to the bookseller
RESUBMIT // Command resubmitted to validator.
Place orders in archived.
As a prescriber, in the order history, in the "Send to bookseller" tab, we see the WAITING, REJECTED, IN_PROGRESS, VALID and RESUBMIT orders which have been archived. The SENT command is still present and has not been modified.
As a validator, in the command history, in the "Send to bookseller" tab, we see the WAITING, …
> feat: #CRRE-605 add archived status constraint to avoid any action on it

- src/main/resources/public/template/prescriptor/campaign-main.html
Addition of the catalog tab for users with access rights.
As a user with access rights, I see the catalog tab when I am in a catalog.
[CRRE-585](https://jira.support-ent.fr/browse/CRRE-585)
> fix: #CRRE-585 fix missing catalog in catalog menu

- src/main/java/fr/openent/crre/helpers/ExportHelper.java
Fix count of distinct structures in an order sent to the bookseller (admin historic)
As an admin, check if the count of structure is correct in historic panel
[CRRE-5622](https://jira.support-ent.fr/browse/CRRE-622)
> fix: #CRRE-622 fix count of structure historic admin

- src/main/java/fr/openent/crre/controllers/EquipmentController.java
- src/main/java/fr/openent/crre/core/constants/Field.java
- src/main/java/fr/openent/crre/model/FilterItemModel.java
Fix search by keyword by adding it to the filter model.
As a user check if you can search by keywords in the catalog
[CRRE-624](https://jira.support-ent.fr/browse/CRRE-624)
> fix(catalog): #CRRE-624 fix search by keyword

- src/main/java/fr/openent/crre/helpers/ElasticSearchHelper.java
- src/main/java/fr/openent/crre/helpers/OrderHelper.java
Added condition to stop NPE if an item doesn't have an offer
Check if you can access to the catalog with an item without offers in db
[CRRE-627](https://jira.support-ent.fr/browse/CRRE-627)
> fix: #CRRE-627 fix NPE when we have an item without offers

- src/main/resources/public/ts/controllers/prescriptor/order/manage-order.ts
A prescriber can submit an order whose article no longer exists
As prescriber send a basket to the validator, refuse it. Then in the history of the prescriber we cannot resubmit this article.
> fix: #CRRE-603 block resubmit order for prescriber when equipment not found

- src/main/java/fr/openent/crre/controllers/ArchiveController.java
When we retrieve the articles we only retrieve the id, we only needed the EAN.
Launch the Archiving API
[CRRE-604](https://jira.support-ent.fr/browse/CRRE-604)
> fix: CRRE-604 fix poor retrieval of fields for articles

- src/main/resources/public/ts/model/Utils.ts
Avoid an undefined
See [CRRE-602](https://jira.support-ent.fr/browse/CRRE-602)
[CRRE-629](https://jira.support-ent.fr/browse/CRRE-629)
> fix: #CRRE-629 fix undefined tva

- src/main/java/fr/openent/crre/controllers/PurseController.java
- src/main/java/fr/openent/crre/exception/ImportPurseException.java
Add errors management when you import purse from csv
Check if it gives you the list of uai which failed if you put for example a string in csv
[CRRE-341](https://jira.support-ent.fr/browse/CRRE-341)
> fix(purses): #CRRE-341 fix error management

- src/main/java/fr/openent/crre/controllers/OrderRegionController.java
- src/main/java/fr/openent/crre/helpers/IModelHelper.java
- src/main/java/fr/openent/crre/model/OrderUniversalModel.java
- src/main/java/fr/openent/crre/model/Purse.java
- src/main/java/fr/openent/crre/service/ProjectService.java
- src/main/java/fr/openent/crre/service/impl/DefaultOrderRegionService.java
- src/main/java/fr/openent/crre/service/impl/DefaultOrderService.java
- src/main/java/fr/openent/crre/service/impl/DefaultProjectService.java
- src/main/java/fr/openent/crre/service/impl/DefaultPurseService.java
- src/test/java/fr/openent/crre/helpers/IModelHelperTest.java
Add optionnal in IModelHelper to avoid NPE.
Send several commands to the regional administrator. Command names increment correctly.
Import credits.
[CRRE-630](https://jira.support-ent.fr/browse/CRRE-630)
> refactor: #CRRE-630 use Optionnal object to avoid NPE

- src/main/resources/public/template/prescriptor/campaign-main.html
- src/main/resources/public/ts/controllers/main.ts
- src/main/resources/public/ts/controllers/prescriptor/campaign-main.ts
When you are as a person having only the right to consult the catalog you must be able to see the "Catalog" tab
https://jira.support-ent.fr/browse/CRRE-585
> fix: #CRRE-585 fix catalog tab not visible

- .github/workflows/dev-check-repository.yml
- .gitignore
- build.sh
- docker-compose.yml
- jest.config.js
- package.json
- src/main/resources/public/sass/global/_crre-specifics.scss
- src/main/resources/public/sass/global/components/_icons.scss
- src/main/resources/public/sass/global/components/_index.scss
- src/main/resources/public/sass/global/fragments/_status-circle.scss
- src/main/resources/public/sass/index.scss
- src/main/resources/view-src/crre.html
- tsconfig.json
Update of the scss compilation + repatriation of the scss from the still-css-lib.
With this modification it will allow us to version the scss.
The tests will be corrected in the next commit.
The css is still there.
> chore: #CRRE-637 make css in module not in entcore-css-lib

- src/main/resources/public/ts/controllers/validator/order-historic.ts
In front when we resubmit an article we have an error.
[CRRE-603](https://jira.support-ent.fr/browse/CRRE-603)
> fix: #CRRE-603 fix unavailable to resubmit order

- src/test/java/fr/openent/crre/helpers/ElasticSearchHelperTest.java
- src/test/java/fr/openent/crre/helpers/ExportHelperTest.java
- src/test/java/fr/openent/crre/service/impl/DefaultBasketOrderItemServiceTest.java
- src/test/java/fr/openent/crre/service/impl/DefaultOrderRegionServiceTest.java
Following a long period of non-execution, the tests were not updated correctly.
> chore: fix test execution

- src/main/resources/public/sass/global/_crre-specifics.scss
- src/main/resources/public/sass/global/components/_index.scss
- src/main/resources/public/sass/global/components/_tooltip.scss
- src/main/resources/public/template/administrator/order/order-waiting.html
- src/main/resources/public/ts/controllers/administrator/order/waitingOrder.ts
- src/main/resources/public/ts/model/Student.ts
As an admin, when I validate the orders I must have access to the number of students per level of the structure.
Place an order on two different establishments and validate them up to the administration. As an administrator, when I hover over the new "Detail" column, a tooltip appears with the number of students per level of the structure.
[CRRE-366](https://jira.support-ent.fr/browse/CRRE-366)
> feat: #CRRE-366 add column details of the number of students (admin interface)

- src/main/java/fr/openent/crre/controllers/PurseController.java
- src/main/java/fr/openent/crre/core/constants/Field.java
- src/main/java/fr/openent/crre/service/PurseService.java
- src/main/java/fr/openent/crre/service/impl/DefaultPurseService.java
Model objects do not pass in a JsonArray. This will cause an exception when modifying credits
The tests are corrected in 1.7-SNAPSHOT (see https://github.com/OPEN-ENT-NG/crre/pull/43)
As an admin, manually modify the credits of a structure.
[CRRE-639](https://jira.support-ent.fr/browse/CRRE-639)
> fix: CRRE-639 fix credits can no longer be changed manually

- src/main/resources/jsonschema/exportOrder.json
- src/main/resources/jsonschema/ordersAmount.json
Forget to authorize the new ARCHIVED value for export in csv rate prescriber.
**The tests are corrected in 1.7-SNAPSHOT**
Perform a CSV export with a prescriber for an order sent to the bookseller.
https://jira.support-ent.fr/browse/CRRE-644
> fix: #CRRE-644 fix unable to launch prescriber csv export (Requests sent to the bookseller)

- src/main/java/fr/openent/crre/model/item/Item.java
- src/main/resources/public/template/prescriptor/catalog/equipment-detail.html
> fix(item): #CRRE-591 fix error when technos is empty

- src/main/java/fr/openent/crre/controllers/BasketController.java
- src/main/java/fr/openent/crre/service/BasketOrderItemService.java
- src/main/java/fr/openent/crre/service/impl/DefaultBasketOrderItemService.java
- src/test/java/fr/openent/crre/service/impl/DefaultBasketOrderItemServiceTest.java
When a prescriber validates a basket and that structure had no credits, there was an error in front.
As a prescriber, placing an order on an establishment that has no credits. The order is sent to the validator, but the latter cannot send it to the regional administrator due to the lack of available credits.
[CRRE-640](https://jira.support-ent.fr/browse/CRRE-640)
> fix: #CRRE-640 prescriber cannot validate basket if establishment has no credits

- src/main/java/fr/openent/crre/service/impl/DefaultPurseService.java
As an admin when you import credits by csv you can reimburse more than the initial amount.
Have an establishment with 100 initial credits and 50 credits remaining. Make a refund of 1000 by CSV import. Initial credits and remaining credits should always be 100.
[CRRE-652](https://jira.support-ent.fr/browse/CRRE-652)
> fix: #CRRE-652 fix possible refund more than original amount

- src/main/java/fr/openent/crre/service/impl/DefaultPurseService.java
When the region administrator imports credits with the addition column is refund credits, he has an error 500
As a regional administrator, import CSV credits by filling in the "Refund" and "Add" columns.
[CRRE-651](https://jira.support-ent.fr/browse/CRRE-651)
> fix: #CRRE-651 fix error when adding & refunding consumables

- src/main/resources/public/sass/global/_crre-specifics.scss
Catalog images are not properly resized.
Go to the catalog, search for "Maskott". The images are well sized.
[CRRE-440](https://jira.support-ent.fr/browse/CRRE-440)
> fix(css): #CRRE-440 fix css for catalog image

- src/main/java/fr/openent/crre/helpers/OrderHelper.java
- src/main/resources/public/ts/model/Equipment.ts
When we have an article without an offer we have undefined in front
Search item 1782701192321
[CRRE-653](https://jira.support-ent.fr/browse/CRRE-653)
> fix: #CRRE-653 fix error when viewing item without offer

- src/main/java/fr/openent/crre/service/impl/DefaultPurseService.java
When adding credits by csv import, the added credits were set and not incremented
En tant qu'admin faire un import avec la colone nouveau crédits. Les crédits ajouter passe a 0
Faire un import avec 100 credits ajouter. Les crédits ajouter passe a 100
Faire un import avec 500 credits ajouter. Les crédits ajouter passe a 600
[CRRE-469](https://jira.support-ent.fr/browse/CRRE-469)
> fix: #CRRE-461 fix added initial amount not incrementing
